
package noumena.payment.mol.ws.querytrx;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "querytrxstatus", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://molv3.molsolutions.com/api/login/s_module/querytrxstatus.asmx?WSDL")
public class Querytrxstatus_
    extends Service
{

    private final static URL QUERYTRXSTATUS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(Querytrxstatus_.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = Querytrxstatus_.class.getResource(".");
            url = new URL(baseUrl, "http://molv3.molsolutions.com/api/login/s_module/querytrxstatus.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://molv3.molsolutions.com/api/login/s_module/querytrxstatus.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYTRXSTATUS_WSDL_LOCATION = url;
    }

    public Querytrxstatus_(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Querytrxstatus_() {
        super(QUERYTRXSTATUS_WSDL_LOCATION, new QName("http://tempuri.org/", "querytrxstatus"));
    }

    /**
     * 
     * @return
     *     returns QuerytrxstatusSoap
     */
    @WebEndpoint(name = "querytrxstatusSoap")
    public QuerytrxstatusSoap getQuerytrxstatusSoap() {
        return super.getPort(new QName("http://tempuri.org/", "querytrxstatusSoap"), QuerytrxstatusSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerytrxstatusSoap
     */
    @WebEndpoint(name = "querytrxstatusSoap")
    public QuerytrxstatusSoap getQuerytrxstatusSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "querytrxstatusSoap"), QuerytrxstatusSoap.class, features);
    }

}
