
package noumena.payment.mol.ws.querytrx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "querytrxstatusSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuerytrxstatusSoap {


    /**
     * 
     * @param mRefID
     * @param merchantID
     * @param heartBeat
     * @param signature
     * @return
     *     returns org.tempuri.QueryOrderStatusResult
     */
    @WebMethod(action = "http://tempuri.org/queryTrxStatus")
    @WebResult(name = "queryTrxStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryTrxStatus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryTrxStatus")
    @ResponseWrapper(localName = "queryTrxStatusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryTrxStatusResponse")
    public QueryOrderStatusResult queryTrxStatus(
        @WebParam(name = "MerchantID", targetNamespace = "http://tempuri.org/")
        String merchantID,
        @WebParam(name = "MRef_ID", targetNamespace = "http://tempuri.org/")
        String mRefID,
        @WebParam(name = "HeartBeat", targetNamespace = "http://tempuri.org/")
        String heartBeat,
        @WebParam(name = "Signature", targetNamespace = "http://tempuri.org/")
        String signature);

    /**
     * 
     * @param mRefID
     * @param merchantID
     * @param signature
     * @return
     *     returns org.tempuri.QueryOrderStatusResult
     */
    @WebMethod(action = "http://tempuri.org/queryTrxDetail")
    @WebResult(name = "queryTrxDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "queryTrxDetail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryTrxDetail")
    @ResponseWrapper(localName = "queryTrxDetailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryTrxDetailResponse")
    public QueryOrderStatusResult queryTrxDetail(
        @WebParam(name = "MerchantID", targetNamespace = "http://tempuri.org/")
        String merchantID,
        @WebParam(name = "MRef_ID", targetNamespace = "http://tempuri.org/")
        String mRefID,
        @WebParam(name = "Signature", targetNamespace = "http://tempuri.org/")
        String signature);

}
