package noumena.payment.model;




/**
 * Callback generated by MyEclipse - Hibernate Tools
 */

public class PayItems  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    private Integer id;
	private String gameid;
	private String serverid;
	private String itemid;
	private int itemprice;
	private String itemdesc;
	private String createtime;
	private String updatetime;


    // Constructors

    /** default constructor */
    public PayItems() {
    }

    /** full constructor */
    public PayItems(Integer id, String gameid, String serverid, String itemid, int itemprice) {
    	this.id = id;
    	this.gameid = gameid;
    	this.serverid = serverid;
    	this.itemid = itemid;
    	this.itemprice = itemprice;
    }

    
    // Property accessors
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
	public String getGameid() {
		return gameid;
	}

	public void setGameid(String gameid) {
		this.gameid = gameid;
	}

	public String getServerid() {
		return serverid;
	}

	public void setServerid(String serverid) {
		this.serverid = serverid;
	}

	public String getItemid() {
		return itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	public int getItemprice() {
		return itemprice;
	}

	public void setItemprice(int itemprice) {
		this.itemprice = itemprice;
	}

	public String getItemdesc() {
		return itemdesc;
	}

	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}

	public String getCreatetime() {
		return createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

}