
package noumena.payment.mol.ws.heartbeat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "heartbeatSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HeartbeatSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRemoteIP", action = "http://tempuri.org/GetRemoteIP")
    @WebResult(name = "GetRemoteIPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRemoteIP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRemoteIP")
    @ResponseWrapper(localName = "GetRemoteIPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRemoteIPResponse")
    public String getRemoteIP();

    /**
     * 
     * @param merchantID
     * @return
     *     returns org.tempuri.HeartBeatResult
     */
    @WebMethod(operationName = "GetHeartBeat", action = "http://tempuri.org/GetHeartBeat")
    @WebResult(name = "GetHeartBeatResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHeartBeat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHeartBeat")
    @ResponseWrapper(localName = "GetHeartBeatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHeartBeatResponse")
    public HeartBeatResult getHeartBeat(
        @WebParam(name = "MerchantID", targetNamespace = "http://tempuri.org/")
        String merchantID);

}
